### ISSUE TITLE
Crash if no directories mounted

### ISSUE THREAD

**Issue by ljlamarche** [EarthCubeInGeo/citationhelper#6]
When running citationhelper in resen with no directories mounted, the program crashes.
```
Traceback (most recent call last):
  File "/home/jovyan/envs/py36/bin/citehelp", line 8, in <module>
    sys.exit(main())
  File "/home/jovyan/envs/py36/lib/python3.6/site-packages/citationhelper/citationhelper.py", line 68, in main
    citehelp(workdirs)
  File "/home/jovyan/envs/py36/lib/python3.6/site-packages/citationhelper/citationhelper.py", line 11, in citehelp
    raise OSError('Cannot find {}'.format(wdir))
OSError: Cannot find /home/jovyan/mount
```
This is because citationhelper by default looks under /home/jovyan/mount and /home/jovyan/work, but /home/jovyan/mount does not exist if there are no directories mounted.  In general, it would be more useful to print a warning if a directory isn't found instead of an error so the program can continue searching other directories.

**Comment by ljlamarche** [comment]
Resolved with #7 .
